---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  ENV_FILE: env.yml

inputs:
  - name: product
  - name: pipelines-repo
  - name: om-cli
  - name: env

run:
  path: pipelines-repo/tasks/upload-product/task.sh
