---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  OPSMAN_CLIENT_ID:
  OPSMAN_CLIENT_SECRET:
  OM_DECRYPTION_PWD:

inputs:
  - name: pipelines-repo
  - name: om-cli

run:
  path: pipelines-repo/tasks/config-opsman/task.sh
