---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  EXTENSION_FILE: extension.json

inputs:
  - name: config
  - name: pipelines-repo
  - name: om-cli

run:
  path: pipelines-repo/tasks/update-vm-extension/task.sh
