---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  OPSMAN_CLIENT_ID:
  OPSMAN_CLIENT_SECRET:
  PRODUCT_NAME:

inputs:
  - name: pipelines-repo
  - name: om-cli
  - name: jq
  - name: tile-config-convertor

run:
  path: pipelines-repo/tasks/generate-config/task.sh
